mtvs-3rd-outsider/master-of-prediction

- src/main/java/com/outsider/masterofprediction/controller/rankPage/RankPageController.java
- src/main/resources/static/css/rank-page/rankpage.css
- src/main/resources/templates/content/rank-page/rank-page.html
- src/main/resources/templates/layout/rank-page/index.html
> 랭킹페이지 타임리프 초안

- src/main/java/com/outsider/masterofprediction/controller/activitypage/ActivityPageController.java
- src/main/resources/static/css/activity-page/activitypage.css
- src/main/resources/templates/content/activity-page/activity-page.html
- src/main/resources/templates/layout/activity-page/index.html
활동내역페이지 타임리프 초안
어떤 변경 사항이 있나요?
> 활동내역페이지 타임리프 초안

- src/main/resources/static/css/header/styles.css
- src/main/resources/templates/fragments/header.html
> feat: header 구조 변경 및 css 변경

- build.gradle
- src/main/java/com/outsider/masterofprediction/controller/AdminCategoryController.java
- src/main/java/com/outsider/masterofprediction/dto/TblCategoryDTO.java
- src/main/java/com/outsider/masterofprediction/dto/constatnt/AdminPaginationConstant.java
- src/main/java/com/outsider/masterofprediction/mapper/CategoryMapper.java
- src/main/java/com/outsider/masterofprediction/provider/DeleteByIdsProvider.java
- src/main/java/com/outsider/masterofprediction/service/CategoryService.java
- src/main/java/com/outsider/masterofprediction/utils/PaginationUtils.java
- src/main/resources/templates/content/admin-page/category/index.html
1. 카테고리 기능 기존 저장소에서 이주작업진행
2. mybatis, lombok, mysql driver 추가 
Resolves: #16
어떤 변경 사항이 있나요?
> category 및 mybatis, lombok 추가

- src/main/java/com/outsider/masterofprediction/dto/TblAttachmentDTO.java
- src/main/java/com/outsider/masterofprediction/mapper/AttachmentMapper.java
이미지 Mapper 및 DTO 추가
Resolves: #25 
어떤 변경 사항이 있나요?
> 이미지 Mapper, DTO 추가

- src/main/java/com/outsider/masterofprediction/MasterOfPredictionApplication.java
- src/main/java/com/outsider/masterofprediction/dto/TblUserDTO.java
- src/main/java/com/outsider/masterofprediction/dto/User.java
- src/main/java/com/outsider/masterofprediction/mapper/UserMapper.java
회원 정보 조회, 갱신, 삭제, 조건부 조회 추가
Resolves: #23 
어떤 변경 사항이 있나요?
> 23 feat user mappe

- build.gradle
- src/main/java/com/outsider/masterofprediction/config/DevAuthenticationFilter.java
- src/main/java/com/outsider/masterofprediction/config/DevSecurityConfig.java
- src/main/java/com/outsider/masterofprediction/dto/CustomUserDetail.java
- src/main/java/com/outsider/masterofprediction/dto/constatnt/StringConstants.java
- src/main/java/com/outsider/masterofprediction/service/UserSession.java
- src/main/resources/application-dev.properties
- src/main/resources/application.properties
프로그램 실행 시 관리자용 계정을 생성하고 반환하여 로그인 수행됬음을 알립니다
Resolves: #27 
어떤 변경 사항이 있나요?
> 27 feat dev security

- src/main/java/com/outsider/masterofprediction/service/FileStorageService.java
- src/main/java/com/outsider/masterofprediction/service/ProcessFileService.java
- src/main/java/com/outsider/masterofprediction/utils/FileUtil.java
- src/main/java/com/outsider/masterofprediction/utils/PreviousFileUtils.java
- src/main/java/com/outsider/masterofprediction/utils/ProcessFileInterface.java
파일 저장, 제거 서비스 추가
Resolves: #28 
어떤 변경 사항이 있나요?
> feat: 파일 저장, 제거 서비스 추가

- src/main/java/com/outsider/masterofprediction/controller/AdminBettingCreateController.java
- src/main/java/com/outsider/masterofprediction/dto/TblSubjectDTO.java
- src/main/java/com/outsider/masterofprediction/dto/constatnt/SubjectStatus.java
- src/main/java/com/outsider/masterofprediction/dto/response/BettingAndAttachmentDTO.java
- src/main/java/com/outsider/masterofprediction/mapper/SubjectMapper.java
- src/main/java/com/outsider/masterofprediction/service/BettingCreateService.java
- src/main/resources/templates/content/admin-page/betting/create.html
관리자페이지에서 배팅등록하는 기능과 ui를 작성하였습니다
어떤 변경 사항이 있나요?
> admin page betting register

- src/main/java/com/outsider/masterofprediction/controller/AdminBettingController.java
- src/main/java/com/outsider/masterofprediction/service/BettingService.java
- src/main/resources/templates/content/admin-page/betting/index.html
관리자 페이지에서 paginnation이 적용된 배팅목록들을 확인할 수 있습니다
Resolves: #35 
어떤 변경 사항이 있나요?
> feat: 관리자 페이지에서의 배팅 조회 및 paginnation 추가

- src/main/resources/templates/content/admin-page/fragments/sidebar.html
공지사항목록, 문의내역, 배팅목록, 티어, 카테고리를 가지는 사이드바를 추가합니다
Resolves: #45 
어떤 변경 사항이 있나요?
> feat: 사이드바 추가

- src/main/java/com/outsider/masterofprediction/controller/AdminNoticeController.java
- src/main/java/com/outsider/masterofprediction/dto/Notice.java
- src/main/java/com/outsider/masterofprediction/dto/TblNoticeDTO.java
- src/main/java/com/outsider/masterofprediction/mapper/NoticeMapper.java
- src/main/java/com/outsider/masterofprediction/service/NoticeService.java
- src/main/resources/templates/content/admin-page/notification/index.html
고정 번호를 기반으로 pagination이 적용된 공지사항 목록을 화면에 출력합니다
Resolves:  #40 
> 40 noti select

- src/main/java/com/outsider/masterofprediction/controller/AdminNoticeCreateController.java
- src/main/java/com/outsider/masterofprediction/controller/AdminNoticeRedirectCreateFormController.java
- src/main/java/com/outsider/masterofprediction/service/NoticeCreateService.java
- src/main/resources/templates/content/admin-page/notification/create.html
공지사항목록에서 등록버튼을 클릭 후 제목과 내용을 입력받아 공지사항을 등록합니다
Resolves: #41  
어떤 변경 사항이 있나요?
> feat: 공지사항 등록ui 및 기능 추가

- src/main/java/com/outsider/masterofprediction/controller/AdminNoticeDeleteByIdController.java
- src/main/java/com/outsider/masterofprediction/service/NoticeDeleteByIdService.java
공지사항 목록에서 삭제할 공지의 체크박스를 체크하고 삭제버튼을 클릭하여 삭제를 진행합니다
Resolves: #47 
어떤 변경 사항이 있나요?
> feat: 공지사항 삭제

- src/main/java/com/outsider/masterofprediction/controller/TierController.java
- src/main/java/com/outsider/masterofprediction/dto/TblTierDTO.java
- src/main/java/com/outsider/masterofprediction/mapper/TierMapper.java
- src/main/java/com/outsider/masterofprediction/service/TierService.java
사용자에게 등급을 부여해주는 티어를 추가합니다
티어를 생성, 삭제, 수정 기능을 추가합니다
Resolves: #53 
어떤 변경 사항이 있나요?
> feat: 티어 추가

- src/main/java/com/outsider/masterofprediction/controller/AdminInquiryController.java
- src/main/java/com/outsider/masterofprediction/dto/CustomTblInquiryDTO.java
- src/main/java/com/outsider/masterofprediction/dto/TblInquiryDTO.java
- src/main/resources/templates/content/admin-page/inquiry/index.html
문의사항 조회 ui 및 기능 추가
Resolves: #52 
어떤 변경 사항이 있나요?
> feat: 문의내역 ui 및 조회기능

- src/main/java/com/outsider/masterofprediction/controller/AdminInquiryReplyController.java
- src/main/java/com/outsider/masterofprediction/controller/AdminInquiryResponseController.java
- src/main/java/com/outsider/masterofprediction/dto/TblInquiryReplyDTO.java
- src/main/java/com/outsider/masterofprediction/dto/constatnt/InquiryReplyStatus.java
- src/main/java/com/outsider/masterofprediction/mapper/InquiryMapper.java
- src/main/java/com/outsider/masterofprediction/mapper/InquiryReplyMapper.java
- src/main/java/com/outsider/masterofprediction/service/InquiryAndReplyResit.java
- src/main/java/com/outsider/masterofprediction/service/InquiryReadService.java
- src/main/java/com/outsider/masterofprediction/service/InquiryReplyCreateService.java
- src/main/java/com/outsider/masterofprediction/service/InquiryStatusUpdateService.java
- src/main/resources/templates/content/admin-page/inquiry/response.html
사용자가 문의한 내용에 답변하는 기능 및 ui 추가
Resolves: #55 
어떤 변경 사항이 있나요?
> feat: 문의답변 ui 및 답변 저장

- src/main/java/com/outsider/masterofprediction/controller/AdminHomeController.java
- src/main/resources/templates/content/admin-page/index.html
- src/main/resources/templates/content/admin-page/tier/index.html
관리자 페이지 접속 시 기본 페이지 초안작성
Resolves: #56 
어떤 변경 사항이 있나요?
> feat: 관리자 기본 페이지 초안

- src/main/java/com/outsider/masterofprediction/config/SecurityConfig.java
- src/main/java/com/outsider/masterofprediction/controller/AdminLoginController.java
- src/main/resources/templates/content/admin-page/betting/result.html
- src/main/resources/templates/content/admin-page/login/index.html
관리자 로그인 페이지 작성
Resolves: #60 
어떤 변경 사항이 있나요?
> feat: 관리자 로그인 페이지 초안

- .gitignore
- src/main/java/com/outsider/masterofprediction/dto/BettingOrderDTO.java
- src/main/java/com/outsider/masterofprediction/service/BettingOrderService.java
- src/main/resources/mapper/BettingOrderMapper.xml
> Feature/67 베팅주문관련

- src/main/java/com/outsider/masterofprediction/controller/BettingController.java
- src/main/resources/static/css/betting-page/batting-active.css
- src/main/resources/static/css/betting-page/batting-body.css
- src/main/resources/static/css/betting-page/batting-graph.css
- src/main/resources/static/css/betting-page/batting-modal.css
- src/main/resources/static/css/betting-page/batting-side.css
- src/main/resources/static/css/betting-page/batting-title.css
- src/main/resources/static/css/betting-page/swich.css
- src/main/resources/static/css/main-page/mainpage.css
- src/main/resources/static/js/betting-page/betting-page-js.js
- src/main/resources/templates/content/betting-page/betting-page.html
> bettingPage-thymleaf

- src/main/java/com/outsider/masterofprediction/dto/CommentDTO.java
- src/main/java/com/outsider/masterofprediction/mapper/CommentMapper.java
- src/main/resources/mapper/CommentMapper.xml
> feat: 댓글관련 서비스,맵퍼,DTO (#71)

- src/main/java/com/outsider/masterofprediction/dto/InquiryDetailDTO.java
- src/main/java/com/outsider/masterofprediction/mapper/InquiryMapper.java
- src/main/java/com/outsider/masterofprediction/service/UserInquiryService.java
- src/main/resources/mapper/InquiryMapper.xml
> feat: 문의 관련 서비스, 맵퍼, DTO (#73)

- src/main/java/com/outsider/masterofprediction/dto/TblBettingOrderDTO.java
- src/main/java/com/outsider/masterofprediction/dto/TblCommentDTO.java
- src/main/java/com/outsider/masterofprediction/dto/UserProfileDTO.java
- src/main/java/com/outsider/masterofprediction/mapper/UserMapper.java
- src/main/java/com/outsider/masterofprediction/service/UserManagementService.java
- src/main/resources/mapper/UserMapper.xml
> Feature/76 사용자관리서비스

- src/main/java/com/outsider/masterofprediction/config/SecurityConfigUser.java
- src/main/java/com/outsider/masterofprediction/controller/MyPageController.java
- src/main/java/com/outsider/masterofprediction/dto/GoogleUserInfo.java
- src/main/java/com/outsider/masterofprediction/dto/OAuth2UserInfo.java
- src/main/java/com/outsider/masterofprediction/dto/UserImageDTO.java
- src/main/java/com/outsider/masterofprediction/dto/UserPaginationDTO.java
- src/main/java/com/outsider/masterofprediction/dto/UserWithdrawalStatusDTO.java
- src/main/java/com/outsider/masterofprediction/dto/constatnt/IntConstants.java
- src/main/java/com/outsider/masterofprediction/mapper/BettingOrderMapper.java
- src/main/java/com/outsider/masterofprediction/service/PrincipalOauthUserService.java
- src/main/resources/application.yml
> Feature/17 마이페이지

- src/main/java/com/outsider/masterofprediction/controller/BettingController.java
- src/main/java/com/outsider/masterofprediction/dto/ActiveDTO.java
- src/main/java/com/outsider/masterofprediction/dto/RankingDTO.java
- src/main/java/com/outsider/masterofprediction/dto/TblBettingOrderDTO.java
- src/main/java/com/outsider/masterofprediction/mapper/BettingOrderMapper.java
- src/main/java/com/outsider/masterofprediction/service/BettingOrderService.java
- src/main/resources/mapper/BettingOrderMapper.xml
> feat : 배팅페이지-활동내역

- src/main/java/com/outsider/masterofprediction/controller/BettingController.java
- src/main/java/com/outsider/masterofprediction/dto/RankingDTO.java
- src/main/java/com/outsider/masterofprediction/mapper/SubjectMapper.java
- src/main/java/com/outsider/masterofprediction/mapper/UserMapper.java
- src/main/java/com/outsider/masterofprediction/service/SubjectService.java
- src/main/java/com/outsider/masterofprediction/service/UserManagementService.java
- src/main/resources/mapper/BettingOrderMapper.xml
- src/main/resources/mapper/UserMapper.xml
- src/main/resources/templates/content/betting-page/betting-page.html
> title-info

- .gitignore
- src/main/java/com/outsider/masterofprediction/config/SecurityConfigUser.java
- src/main/java/com/outsider/masterofprediction/controller/LoginController.java
- src/main/java/com/outsider/masterofprediction/controller/MainPageController.java
- src/main/java/com/outsider/masterofprediction/dto/GoogleUserInfo.java
- src/main/java/com/outsider/masterofprediction/dto/OAuth2UserInfo.java
- src/main/java/com/outsider/masterofprediction/service/PrincipalOauthUserService.java
- src/main/java/com/outsider/masterofprediction/service/UserManagementService.java
- src/main/resources/application-dev.properties
- src/main/resources/application-user.properties
- src/main/resources/application.properties
- src/main/resources/application.yml
- src/main/resources/static/css/login-page/login-page.css
- src/main/resources/static/scss/login-page/common.css
- src/main/resources/static/scss/login-page/common.scss
- src/main/resources/templates/content/login-page/login.html
- src/main/resources/templates/content/login-page/register.html
- src/main/resources/templates/fragments/header.html
> feat: 로그인 기능 (#91)

- src/main/resources/static/css/betting-page/batting-active.css
- src/main/resources/static/js/betting-page/betting-page-js.js
- src/main/resources/static/js/betting-page/temp.js
- src/main/resources/templates/content/betting-page/betting-page.html
> 75 배팅페이지 활동내역 구현

- src/main/java/com/outsider/masterofprediction/controller/ImageController.java
> feat: 이미지 컨트롤러 기능 (#99)

- src/main/java/com/outsider/masterofprediction/controller/MyPageController.java
- src/main/java/com/outsider/masterofprediction/dto/BettingInfoDTO.java
- src/main/java/com/outsider/masterofprediction/service/BettingOrderService.java
- src/main/resources/mapper/BettingOrderMapper.xml
- src/main/resources/templates/content/my-page/my-page.html
> fix: 베팅 인사이트 sql 에러 , 이상해진 마이페이지 수정 (#106)

- src/main/java/com/outsider/masterofprediction/controller/BettingController.java
- src/main/java/com/outsider/masterofprediction/dto/CommentReDTO.java
- src/main/java/com/outsider/masterofprediction/dto/TblReplyDTO.java
- src/main/java/com/outsider/masterofprediction/mapper/CommentMapper.java
- src/main/java/com/outsider/masterofprediction/mapper/ReplyMapper.java
- src/main/java/com/outsider/masterofprediction/service/CommentService.java
- src/main/java/com/outsider/masterofprediction/service/ReplyService.java
- src/main/resources/mapper/CommentMapper.xml
- src/main/resources/mapper/ReplyMapper.xml
- src/main/resources/static/css/betting-page/batting-active.css
- src/main/resources/static/js/betting-page/betting-page-js.js
- src/main/resources/templates/content/betting-page/betting-page.html
> 86-betting-commnet

- src/main/java/com/outsider/masterofprediction/controller/MainPageController.java
- src/main/java/com/outsider/masterofprediction/mapper/MainPageSubjectMapper.java
- src/main/java/com/outsider/masterofprediction/service/MainPageService.java
- src/main/resources/static/css/main-page/mainpage.css
- src/main/resources/templates/content/main-page/main-page.html
메인페이지의 더미 데이터를 제거하고 데이텅베이스와 연동하였습니다
Resolves: #113 
어떤 변경 사항이 있나요?
> feat: 메인페이지 데이터베이스 연동

- src/main/java/com/outsider/masterofprediction/controller/MainPageController.java
- src/main/java/com/outsider/masterofprediction/dto/response/MainPageSubjectDTO.java
- src/main/java/com/outsider/masterofprediction/mapper/MainPageSubjectMapper.java
- src/main/java/com/outsider/masterofprediction/service/MainPageService.java
- src/main/resources/static/css/main-page/mainpage.css
- src/main/resources/templates/content/main-page/main-page.html
누락된 DTO 추가합니다
Resolves: #113 
어떤 변경 사항이 있나요?
> fix: 누락된 DTO

- build.gradle
- src/main/resources/application.properties
- src/main/resources/templates/content/main-page/main-page.html
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/fragments/logout-header-profile.html
- src/main/resources/templates/fragments/mobileHeader.html
- src/main/resources/templates/layout/main-page/index.html
모바일 쪽은 아직 추가 못함
어떤 변경 사항이 있나요?
> feat: 헤더 로그인 로그아웃 인증에 따라 변경(#116)

- src/main/java/com/outsider/masterofprediction/controller/BettingAddPageController.java
- src/main/resources/static/css/main-page/mainpage.css
- src/main/resources/templates/fragments/betting-add.html
- src/main/resources/templates/layout/main-page/index.html
resolve: #119 
메인페이지에서 배팅게임 등록 폼 접근 UI.
배팅게임 등록 폼 기능.
> feat: 배팅 게임 등록 진입점 + 컨트롤러

- src/main/java/com/outsider/masterofprediction/config/DevSecurityConfig.java
- src/main/java/com/outsider/masterofprediction/config/SecurityConfigAutoLogin.java
- src/main/java/com/outsider/masterofprediction/config/SecurityConfigUser.java
- src/main/resources/application-user.properties
- src/main/resources/application.properties
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/fragments/mobileHeader.html
- src/main/resources/templates/fragments/mypage-desktop-header.html
- src/main/resources/templates/fragments/mypage-mobile-header.html
- src/main/resources/templates/layout/main-page/index.html
헤더 로그인 로그아웃 모바일 , 데스크탑 기능 연결
#126
어떤 변경 사항이 있나요?
> feat: 헤더 로그인 로그아웃 기능 (#126)

- src/main/java/com/outsider/masterofprediction/controller/ActivityPageController.java
- src/main/java/com/outsider/masterofprediction/dto/ActivityUserSubjectDTO.java
- src/main/java/com/outsider/masterofprediction/mapper/BettingOrderMapper.java
- src/main/java/com/outsider/masterofprediction/service/ActivityFindService.java
- src/main/resources/mapper/BettingOrderMapper.xml
- src/main/resources/templates/content/activity-page/activity-page.html
활동내역페이지 조회 기능 추가
활동내역을 최신 순으로 정렬하여 표시
어떤 변경 사항이 있나요?
> 121-activitypage-find

- src/main/java/com/outsider/masterofprediction/config/DevSecurityConfig.java
- src/main/java/com/outsider/masterofprediction/controller/BettingController.java
- src/main/java/com/outsider/masterofprediction/mapper/UserMapper.java
- src/main/java/com/outsider/masterofprediction/service/UserManagementService.java
- src/main/resources/mapper/UserMapper.xml
- src/main/resources/static/css/betting-page/batting-title.css
- src/main/resources/static/js/betting-page/betting-page-js.js
- src/main/resources/templates/content/betting-page/betting-page.html
> feat : betting-warning and have point

- src/main/java/com/outsider/masterofprediction/dto/TblTierDTO.java
- src/main/java/com/outsider/masterofprediction/dto/TblUserDTO.java
- src/main/java/com/outsider/masterofprediction/service/TierService.java
티어관련 DTO 추가 및 이미지를 추가하였습니다
어떤 변경 사항이 있나요?
> feat: 티어 이미지 및 UserDTO에 티어 추가, 티어 DTO 추가

- src/main/java/com/outsider/masterofprediction/MasterOfPredictionApplication.java
- src/main/java/com/outsider/masterofprediction/dto/TblTierDTO.java
- src/main/java/com/outsider/masterofprediction/dto/TblUserDTO.java
- src/main/java/com/outsider/masterofprediction/mapper/UserMapper.java
- src/main/java/com/outsider/masterofprediction/service/TierScheduledTasks.java
- src/main/java/com/outsider/masterofprediction/service/TierService.java
5분간격으로 티어를 갱신하는 로직을 추가하였습니다
Resolves: #140 
어떤 변경 사항이 있나요?
> 티어 자동 갱신 추가

- src/main/java/com/outsider/masterofprediction/controller/MyPageController.java
- src/main/java/com/outsider/masterofprediction/dto/CustomUserDetail.java
- src/main/java/com/outsider/masterofprediction/dto/User.java
- src/main/java/com/outsider/masterofprediction/mapper/AttachmentMapper.java
- src/main/java/com/outsider/masterofprediction/mapper/TierMapper.java
- src/main/java/com/outsider/masterofprediction/service/TierService.java
- src/main/resources/application.properties
- src/main/resources/mapper/AttachmentMapper.xml
- src/main/resources/mapper/TierMapper.xml
- src/main/resources/templates/content/my-page/my-page.html
> feat: 티어연동 (#124)

- src/main/java/com/outsider/masterofprediction/controller/MainPageController.java
- src/main/java/com/outsider/masterofprediction/dto/constatnt/IntConstants.java
- src/main/java/com/outsider/masterofprediction/mapper/BettingOrderMapper.java
- src/main/resources/mapper/BettingOrderMapper.xml
- src/main/resources/templates/fragments/activity.html
메인페이지의 활동내역을 더미데이터에서 DB 데이터로 연동하였습니다
어떤 변경 사항이 있나요?
> feat: 메인페이지 활동내역

- src/main/java/com/outsider/masterofprediction/controller/CategoryController.java
- src/main/java/com/outsider/masterofprediction/dto/CategoryPageSubjectDTO.java
- src/main/java/com/outsider/masterofprediction/mapper/CategoryPageSubjectMapper.java
- src/main/java/com/outsider/masterofprediction/service/CategoryPageService.java
- src/main/resources/application.properties
- src/main/resources/mapper/CategoryPageSubjectMapper.xml
- src/main/resources/templates/content/category/category.html
헤더의 카테고리를 선택하여 해당 카테고리의 베팅 게임을 조회할 수 있다.
어떤 변경 사항이 있나요?
> 135-category-based-search

- src/main/resources/templates/content/main-page/main-page.html
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/layout/category/index.html
메인페이지에서 View All 클릭 시 전체 상품을 보여줍니다
어떤 변경 사항이 있나요?
> 148-main-page-view-all

- src/main/java/com/outsider/masterofprediction/controller/ActivityPageController.java
- src/main/java/com/outsider/masterofprediction/controller/RankPageController.java
- src/main/resources/templates/fragments/header.html
헤더 수정
- 활동내역페이지 헤더에 카테고리가 정상적으로 보이지 않는 문제 수정
- 랭킹페이지에서 헤더에 카테고리가 정상적으로 보이지 않는 문제 수정
- 헤더의 활동내역 페이지 버튼이 정상 동작하지 않는 문제 수정
어떤 변경 사항이 있나요?
> 156-header-modification

- src/main/resources/templates/content/notice-page/index.html
resolves: #163 
어떤 변경 사항이 있나요?
> hotfix: 공지사항 번호 수정

- src/main/java/com/outsider/masterofprediction/config/DevSecurityConfig.java
- src/main/java/com/outsider/masterofprediction/dto/CustomUserDetail.java
- src/main/java/com/outsider/masterofprediction/dto/UserSubjectDTO.java
- src/main/java/com/outsider/masterofprediction/mapper/BettingOrderMapper.java
- src/main/java/com/outsider/masterofprediction/mapper/UserMapper.java
- src/main/java/com/outsider/masterofprediction/service/SubjectService.java
- src/main/java/com/outsider/masterofprediction/service/UserManagementService.java
- src/main/resources/mapper/BettingOrderMapper.xml
> feat: 정산 기능 #173

- src/main/java/com/outsider/masterofprediction/service/SettlementScheduledTasks.java
- src/main/java/com/outsider/masterofprediction/service/SubjectService.java
베팅 종료시간을 체크해서 정산 상태로 바꾸는 기능 #175
#175
어떤 변경 사항이 있나요?
> feature:베팅 종료시간을 체크해서 정산 상태로 바꾸는 기능 #175

- src/main/java/com/outsider/masterofprediction/controller/AdminBettingResultController.java
- src/main/java/com/outsider/masterofprediction/dto/constatnt/StringConstants.java
- src/main/java/com/outsider/masterofprediction/mapper/SubjectMapper.java
- src/main/java/com/outsider/masterofprediction/service/BettingResultService.java
- src/main/java/com/outsider/masterofprediction/service/SubjectService.java
- src/main/java/com/outsider/masterofprediction/service/UserManagementService.java
- src/main/resources/static/css/admin-page/betting/index.css
- src/main/resources/static/css/admin-page/index.css
- src/main/resources/templates/content/admin-page/betting/index.html
- src/main/resources/templates/content/admin-page/betting/result.html
- src/main/resources/templates/content/admin-page/betting/update.html
배팅 결과 서비스를 추가하였습니다
Resolves: #170 
어떤 변경 사항이 있나요?
> 배팅결과 서비스 추가

- src/main/java/com/outsider/masterofprediction/service/SubjectService.java
상품 상태 체크해서 정산 상태로 변경하는 함수를 수정하였습니다
Resolves: #179 
어떤 변경 사항이 있나요?
> fix: subject status scheduling update

- src/main/java/com/outsider/masterofprediction/controller/TierViewController.java
- src/main/resources/static/css/tier/tier.css
- src/main/resources/templates/content/tier/tier.html
tier css 수정 및 controller 추가
어떤 변경 사항이 있나요?
> feat: tier controller add, tier css update

- src/main/resources/templates/layout/category/index.html
우하단 베팅 게임 등록 버튼 동작 오류 수정
어떤 변경 사항이 있나요?
> 186-betting-regist-button-bug-fix

- src/main/resources/templates/fragments/login-header-profile.html
- src/main/resources/templates/fragments/mypage-mobile-header.html
- src/main/resources/templates/layout/my-page/index.html
> mypage 해더 반응형

- src/main/resources/application-autoLogin.properties
- src/main/resources/application-dev.properties
- src/main/resources/application-user.properties
- src/main/resources/application.properties
- src/main/resources/application.yml
properties 개인 설정과 공통 설정으로 나누기
#194 
어떤 변경 사항이 있나요?
> properties 개인 설정과 공통 설정으로 나누기

- src/main/java/com/outsider/masterofprediction/mapper/MainPageSubjectMapper.java
- src/main/java/com/outsider/masterofprediction/service/SubjectService.java
> 메인페이지 상품의 조건을 변경했습니다

- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/fragments/mobileHeader.html
- src/main/resources/templates/fragments/mypage-desktop-header.html
- src/main/resources/templates/fragments/mypage-mobile-header.html
-티어 페이지
-랭킹 페이지
-활동 페이지
#197 
어떤 변경 사항이 있나요?
> 해더의 햄버거에 라우팅

- my.cnf
- src/main/resources/schema.sql
> feat: full text index 추가

- src/main/java/com/outsider/masterofprediction/controller/SearchPageController.java
- src/main/java/com/outsider/masterofprediction/dto/SearchPageSubjectDTO.java
- src/main/java/com/outsider/masterofprediction/mapper/SearchPageMapper.java
- src/main/java/com/outsider/masterofprediction/service/SearchPageService.java
- src/main/resources/application.properties
- src/main/resources/data.sql
- src/main/resources/mapper/SearchPageMapper.xml
- src/main/resources/templates/content/search/search.html
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/layout/search/index.html
검색어를 기반으로 베팅 게임을 검색할 수 있도록 함.
어떤 변경 사항이 있나요?
> 159-searching-word-based-search

- src/main/java/com/outsider/masterofprediction/controller/BettingController.java
- src/main/resources/static/js/betting-page/betting-page-js.js
betting profile link기능
어떤 변경 사항이 있나요?
> feat : betting profile link

- src/main/java/com/outsider/masterofprediction/config/DevAuthenticationFilter.java
- src/main/java/com/outsider/masterofprediction/config/LogOutConfig.java
- src/main/java/com/outsider/masterofprediction/controller/MyPageController.java
- src/main/java/com/outsider/masterofprediction/dto/User.java
- src/main/java/com/outsider/masterofprediction/service/UserManagementService.java
> feat : logout

- src/main/java/com/outsider/masterofprediction/controller/SearchPageController.java
- src/main/resources/templates/content/search.html
- src/main/resources/templates/fragments/header.html
> 225-header-search-bar-modification

- src/main/java/com/outsider/masterofprediction/controller/ActivityPageController.java
- src/main/java/com/outsider/masterofprediction/controller/RankPageController.java
- src/main/java/com/outsider/masterofprediction/dto/ActivityUserSubjectDTO.java
- src/main/java/com/outsider/masterofprediction/dto/UserAttachmentDTO.java
- src/main/resources/application.properties
- src/main/resources/templates/content/rank-page.html
이미지 로딩 오류 수정
랭킹페이지 이미지 로딩 오류 수정
활동내역페이지 이미지 로딩 오류 수정
메인페이지 이미지 로딩 오류 수정
어떤 변경 사항이 있나요?
> 229-image-loading-bug-fix

- src/main/java/com/outsider/masterofprediction/service/BettingOrderService.java
> feat : nullException

- src/main/java/com/outsider/masterofprediction/controller/BettingController.java
- src/main/resources/static/css/betting-page/batting-modal.css
- src/main/resources/static/js/betting-page/betting-page-js.js
- src/main/resources/templates/content/betting-page/betting-page.html
정산하기 모달 구현 & 클릭 시 결과값 서버 전송
어떤 변경 사항이 있나요?
> feat: 정산하기 모달 구현 & 클릭 시 결과값 서버 전송

- src/main/resources/templates/content/betting-page.html
> feat: 정산하기 버튼 구현2

- src/main/resources/static/css/betting-page/batting-modal.css
- src/main/resources/static/js/betting-page/betting-page-js.js
> feat: 정산하기 모달 구현3

- src/main/resources/static/css/betting-page/batting-modal.css
- src/main/resources/static/js/betting-page/betting-page-js.js
> feat: 정산하기 모달 구현4

- src/main/java/com/outsider/masterofprediction/controller/BettingController.java
- src/main/resources/static/css/betting-page/batting-modal.css
- src/main/resources/static/js/betting-page/betting-page-js.js
> feat: 정산하기 모달 구현하기5

- src/main/java/com/outsider/masterofprediction/controller/BettingController.java
- src/main/resources/static/js/betting-page/betting-page-js.js
> feat: 정산하기 모달 구현6

- .gitignore
Resolves: #243 
어떤 변경 사항이 있나요?
> feat: application.properties 경로 수정

- src/main/java/com/outsider/masterofprediction/controller/SearchPageController.java
- src/main/java/com/outsider/masterofprediction/mapper/SearchPageMapper.java
- src/main/java/com/outsider/masterofprediction/service/SearchPageService.java
- src/main/resources/mapper/SearchPageMapper.xml
검색 방식 수정
입력된 문자열을 공백문자 단위로 파싱
boolean mode에서 LIKE CONCAT을 이용한 문자열 비교 방식으로 변경
어떤 변경 사항이 있나요?
> 245-search-method-modification

- src/main/resources/static/css/betting-page/batting-graph.css
- src/main/resources/static/css/betting-page/batting-side.css
- src/main/resources/static/css/betting-page/batting-title.css
- src/main/resources/static/css/betting-page/betting-respon.css
- src/main/resources/static/js/betting-page/betting-page-js.js
- src/main/resources/templates/content/betting-page.html
> feat : betting mobile
